# Generated by Django 5.0.4 on 2024-04-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='spam',
        ),
    ]
