# Generated by Django 5.0.4 on 2024-04-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_user_profile_spam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
