# Generated by Django 5.0.4 on 2024-04-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_user_profile_user_user_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='user',
        ),
        migrations.AddField(
            model_name='contacts',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user_profile'),
        ),
    ]
