# Generated by Django 5.0.4 on 2024-04-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_contacts_user_contacts_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
