# Generated by Django 5.0.4 on 2024-04-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_name_user_profile_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
